-- 1. CLEANUP: Drop existing tables to allow for a clean import
-- Note: PL/SQL block handles errors if tables don't exist yet
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE events CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE locations CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN IF SQLCODE != -942 THEN RAISE; END IF;
END;
/

-- 2. LOCATIONS TABLE
CREATE TABLE locations (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR2(255) NOT NULL,
    sector_code  VARCHAR2(50) NOT NULL,
    description  CLOB,
    image_url    VARCHAR2(1000), -- Increased length for long URLs
    CONSTRAINT locations_sector_unique UNIQUE (sector_code)
);

-- 3. EVENTS TABLE
CREATE TABLE events (
    id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_id  NUMBER,
    title        VARCHAR2(255) NOT NULL,
    start_date   TIMESTAMP NOT NULL,
    organizer    VARCHAR2(255),
    details      CLOB,
    event_type   VARCHAR2(50),
    CONSTRAINT fk_events_location FOREIGN KEY (location_id) 
        REFERENCES locations(id) ON DELETE SET NULL
);

-- 4. COMMENTS (These will appear in Data Modeler Notes)
COMMENT ON TABLE locations IS 'The clickable areas on the frontend';
COMMENT ON COLUMN locations.sector_code IS 'Used for URL paths/API requests (e.g., HYDRO, ADMIN)';
COMMENT ON TABLE events IS 'The data displayed on the detail pages';
